insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Lotstring', 710, 'Divanoodle', 'Laptop', 56, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bitwolf', 508, 'Kaymbo', 'Desktop', 11, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Tin', 600, 'Wordpedia', 'Smart Phone', 72, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Aerified', 779, 'Meevee', 'Smart Phone', 18, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Alphazap', 472, 'Eire', 'Desktop', 89, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zathin', 639, 'Photospace', 'Desktop', 22, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zaam-Dox', 312, 'Avamba', 'Smart Phone', 17, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bitwolf', 760, 'Divanoodle', 'Laptop', 73, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Voltsillam', 965, 'Flipstorm', 'Desktop', 99, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bytecard', 686, 'Mita', 'Smart Phone', 98, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Job', 366, 'Topicblab', 'Smart Phone', 14, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zaam-Dox', 875, 'Skiptube', 'Tablet', 20, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Veribet', 915, 'Quimba', 'Smart Phone', 67, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Stronghold', 869, 'Snaptags', 'Laptop', 48, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Andalax', 324, 'Topdrive', 'Accessory', 53, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Asoka', 480, 'Dynabox', 'Accessory', 97, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zaam-Dox', 509, 'Skidoo', 'Smart Phone', 38, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Sonair', 340, 'Oyoba', 'Laptop', 90, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Gembucket', 660, 'Vitz', 'Smart Phone', 3, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Sonair', 753, 'Zoombox', 'Tablet', 15, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Voltsillam', 657, 'Wordtune', 'Tablet', 46, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bamity', 638, 'Yadel', 'Desktop', 38, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Flexidy', 572, 'Vinder', 'Accessory', 62, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bitwolf', 747, 'Rhycero', 'Laptop', 28, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Stim', 515, 'Roombo', 'Laptop', 98, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zathin', 438, 'Jayo', 'Tablet', 78, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zamit', 953, 'Layo', 'Smart Phone', 37, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Regrant', 846, 'Skinix', 'Accessory', 66, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Sonair', 354, 'Oyoyo', 'Laptop', 23, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bitchip', 969, 'Dabvine', 'Accessory', 32, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bitwolf', 984, 'Yodo', 'Accessory', 33, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Kanlam', 330, 'Shuffledrive', 'Desktop', 77, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Fixflex', 706, 'Riffpedia', 'Accessory', 82, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Sub-Ex', 897, 'Gabtune', 'Desktop', 71, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Tresom', 976, 'Feedfire', 'Tablet', 35, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zoolab', 653, 'Yakidoo', 'Accessory', 75, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Overhold', 963, 'Layo', 'Desktop', 74, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Rank', 422, 'Vinte', 'Tablet', 82, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Bytecard', 532, 'Trudoo', 'Smart Phone', 56, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Voltsillam', 836, 'Wikibox', 'Smart Phone', 38, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Kanlam', 890, 'Edgetag', 'Laptop', 82, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Fixflex', 578, 'Mycat', 'Tablet', 81, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Flowdesk', 553, 'Skivee', 'Laptop', 22, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Tempsoft', 450, 'Centidel', 'Accessory', 61, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Cardify', 974, 'Thoughtblab', 'Laptop', 19, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zathin', 860, 'Linklinks', 'Accessory', 83, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Zathin', 710, 'Twimm', 'Tablet', 59, 'Used');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Matsoft', 742, 'Quinu', 'Accessory', 71, 'New');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Holdlamis', 393, 'Youspan', 'Accessory', 81, 'Refurbished');
insert into `webstore`.`product` (`name`, `unitprice`, `manufacturer`, `category`, `unitsinstock`, `condition`) values ('Quo Lux', 668, 'Oloo', 'Accessory', 43, 'Used');
